language: android
dist: xenial

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

before_install:
  - cd app
  - openssl aes-256-cbc -K $encrypted_5f0d05c9e57c_key -iv $encrypted_5f0d05c9e57c_iv -in google-services.json.enc -out google-services.json -d
  - cd ..
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

before_script:
  - chmod +x gradlew
  - mkdir -p ~/.gradle
  - echo openLiveTriviaFirebaseServerClientId=$FIREBASE_SERVER_CLIENT_ID >> ~/.gradle/gradle.properties

script:
  - ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m clean build

after_script:
  - rm -vf ./app/google-services.json
  - rm -vf ~/gradle/gradle.properties